# Change these first
owner: CaCatHead # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: CaCatHead
    url: https://cacathead.cn
  - name: XLorPaste OJ
    url: https://oj.xlorpaste.cn
  - name: Docs
    url: https://docs.cacathead.cn
  - name: Upptime
    url: https://upptime.cacathead.cn

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: upptime.cacathead.cn
  # baseUrl: /your-repo-name
  logoUrl: https://cacathead.cn/favicon.png
  name: CaCatHead Upptime
  introTitle: CaCatHead Status Monitor
  introMessage: Use **real-time** data from our [Github repository](https://github.com/koj-co/upptime) powered by open-source uptime monitor **Upptime** and **GitHub**.
  navbar:
    - title: Status
      href: /
    - title: CaCatHead
      href:  https://cacathead.cn
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
